### ISSUE TITLE
"Caching active record queries is currently disabled on RedisMemo"

### ISSUE THREAD

**Issue by Overload119** [chanzuckerberg/redis-memo#97]
I just installed this gem.

```
# typed: true
RedisMemo.configure do |config|
  config.expires_in = 3.hours
  config.global_cache_key_version = SecureRandom.uuid
  config.redis = Rails.application.credentials.redis
end
```

What causes this?

Seems to be this line:

```
unless connection.respond_to?(:dependency_of)
  raise RedisMemo::WithoutMemoization.new('Caching active record queries is currently disabled on RedisMemo')
end
```

Where is `dependency_of` defined?

**Comment by katyho** [comment]
Are you trying to cache ActiveRecord queries? If so, you need to do so explicitly by specifying which columns you want to memoize, see https://github.com/chanzuckerberg/redis-memo#cache-simple-activerecord-queries .

For reference, this is where [dependency_of](https://github.com/chanzuckerberg/redis-memo/blob/38c5b02932495f25a0bf90b1bf8a403fe112ab2c/lib/redis_memo/memoize_method.rb#L86) is defined.
